env:
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
      language: objective-c
      osx_image: xcode10.1
      env:
        - JOB_NAME=IOS
      before_install:
        - nvm install 11
        - node --version
      install:
        - npm install
        - npm run link
      script:
        - npm run check
        - npm run build:ios
  include:
    - language: node_js
      node_js: "node"
      script:
        - npm list
        - npm run check

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-21
          - android-27
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - JOB_NAME=ANDROID
      before_install:
        - nvm install 11
        - node --version
      install:
        - npm install
        - npm run link
      script:
        - npm run check
        - npm run build:android
